version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ronaldo
      POSTGRES_PASSWORD: bigdata
      POSTGRES_DB: bigdata
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
